config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "events#index"
  resources :events, only: [:index, :create, :show, :new, :destroy, :edit, :update]
  resources :event_attendances, only: [:create, :destroy]
  get "my_events" => "events#my_events"
  get "my_created_events" => "events#my_created_events"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id

  has_many :event_attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :event_attendances, source: :attendee

  has_many :invitations, dependent: :destroy
  has_many :invitees, through: :invitations, source: :invitee

  validates :name, :date, :location, presence: true
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  # This is a join table between User and Event

  # This event_attendance record belongs to attendee
  belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
  # This event_attendance record belongs to attended_event
  belongs_to :attended_event, class_name: 'Event', foreign_key: :attended_event_id

  # prevent duplicate registration
  validates :attendee_id, uniqueness: { scope: :attended_event_id, message: 'You have already registered for this event.'}
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :inviter, class_name: 'User'
  belongs_to :invitee, class_name: 'User'
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: :creator_id

  has_many :event_attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendances

  has_many :invitations_sent, foreign_key: :inviter_id, class_name: 'Invitation'
  has_many :invitations_received, foreign_key: :invitee_id, class_name: 'Invitation'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  def create
    # @event = Event.find(params[:event_id])
    # @event_attendance = @event.event_attendances.build(attendee_id: current_user.id)
    @event_attendance = current_user.event_attendances.build(attended_event_id: params[:event_id])
    if @event_attendance.save
      redirect_to event_path(params[:event_id]), notice: 'You have successfully registered for this event.'
    else
      redirect_to event_path(params[:event_id]), alert: @event_attendance.errors.full_messages.to_sentence
    end
  end

  def destroy
    @event_attendance = EventAttendance.find_by(attended_event_id: params[:event_id], attendee_id: current_user.id)
    @event_attendance.destroy
    redirect_to event_path(@event_attendance.attended_event_id), notice: 'You have successfully unregistered for this event.'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    # @events = Event.all
    @past_events = Event.where('date < ?', Date.today)
    @upcoming_events = Event.where('date >= ?', Date.today)
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      if @event.private
        invitee_ids = params[:event][:invitee_ids].reject(&:blank?)
        invitee_ids.each do |invitee_id|
          Invitation.create(inviter_id: current_user.id, invitee_id: invitee_id, event_id: @event.id) if invitee_id.present?
        end
      end
      redirect_to my_created_events_path, notice: 'Event was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def my_events
    @my_attended_events = current_user.attended_events
  end

  def my_created_events
    @created_events = current_user.created_events
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: 'Event was successfully deleted.'
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      @event.invitations.destroy_all
      if @event.private
        invitee_ids = params[:event][:invitee_ids].reject(&:blank?)
        invitee_ids.each do |invitee_id|
          Invitation.create(inviter_id: current_user.id, invitee_id: invitee_id, event_id: @event.id) if invitee_id.present?
        end
      end
      redirect_to event_path(@event), notice: 'Event was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :location, :date, :private)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for(@event, html: {class: 'event-form'}, data: { controller: "event-form" } ) do |f| %> 
  <% if @event.errors.any? %>
    <div id="error">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>

  <div class="field">
    <%= f.label :private, 'Private Event?'%>
    <%= f.check_box :private, data: { event_form_target: "private", action: "event-form#updateInviteesField" } %>
  </div>

  <div class="field invitees-field" data-event-form-target="invitees">
    <%= f.label :invitees %><br>
    <%# f.collection_select :invitee_ids, User.all, :id, :name, {}, {multiple: true} %>
    <%= f.collection_check_boxes :invitee_ids, User.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit "Update Event"%>
  </div>
<% end %>

app/views/events/index.html.erb
<h1>All Events</h1> 

<h2>Upcoming Events</h2>
<% @upcoming_events.each do |event| %>
  <% if !event.private || event.invitees.include?(current_user) %>
    <div class="event-div">
      <h3><%= link_to event.name, event_path(event) %></h3>
      <p><b>Date:</b> <%= event.date %></p>
      <p><b>Location:</b> <%= event.location %></p>
    </div>
  <% end %>
<% end %>

<h2>Past Events</h2>
<% @past_events.each do |event| %>
  <% if !event.private || event.invitees.include?(current_user) %>
    <div class="event-div">
      <h3><%= link_to event.name, event_path(event) %></h3>
      <p><b>Date:</b> <%= event.date %></p>
      <p><b>Location:</b> <%= event.location %></p>
    </div>
  <% end %>
<% end %>

app/views/events/my_created_events.html.erb
<h1>Your Created Events</h1>

<p class="new-event"> <%= link_to 'Create a new Event', new_event_path %> </p>

<% @created_events.each do |event| %>
  <div class="event-div">
  <h2><%= event.name %></h2>
  <p><%= event.date %></p>
  <p><%= event.location %></p>
  <p><%= link_to 'Edit this event', edit_event_path(event) %></p>
  <p><%= button_to "Delete this event", event_path(event), method: :delete, data: { confirm: "Are you sure?", } %></p> <br>
  </div>
<%end%>

app/views/events/my_events.html.erb
<h1>Your Attended Events</h1>

<h2>Future Events</h2>
<% @my_attended_events.each do |event| %>
  <% if event.date > Time.now %>
    <div class="event-div">
      <h3><%= event.name %></h3>
      <p><%= event.date %></p>
      <p><%= event.location %></p>
    </div>
  <% end %>
<% end %>

<h2>Past Events</h2>
<% @my_attended_events.each do |event| %>
  <% if event.date <= Time.now %>
    <div class="event-div">
      <h3><%= event.name %></h3>
      <p><%= event.date %></p>
      <p><%= event.location %></p>
    </div>
  <% end %>
<% end %>

app/views/events/new.html.erb
<h2>Create an event</h2>

<%= form_with model: @event, html: {class: 'event-form'}, data: { controller: "event-form" } do |f| %>
    <% if @event.errors.any? %>
        <div id="error">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
            <ul>
                <% @event.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <div class="field private-event">
    <%= f.label :private, 'Private Event?'%>
    <%= f.check_box :private, data: { event_form_target: "private", action: "event-form#updateInviteesField" } %>
  </div>

  <div class="field invitees-field" data-event-form-target="invitees">
    <%= f.label :invitees %> <br>
    <%= f.collection_select :invitee_ids, User.all, :id, :name, {}, {multiple: true} %>
    <%# f.select :invitee_ids, User.all.collect { |u| [u.name, u.id] }, {}, { multiple: true } %> 
  </div>

  <div class="actions">
    <%= f.submit "Create Event"%>
  </div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><strong>Date:</strong> <%= @event.date %></p>
<p><strong>Location:</strong> <%= @event.location %></p>
<p><strong>Creator:</strong> <%= @event.creator.name %></p>
<% if @event.attendees.include?(current_user) %>
    <p> <%= button_to 'Cancel Attendance', event_attendance_path(event_id: @event.id), method: :delete, data: { turbo_method: :delete } %> </p>
<% else %>
    <p> <%= button_to 'Attend Event', event_attendances_path(event_id: @event.id) %> </p>
<% end %>

<h2>Attendees</h2>
<div class="attendees">
    <ol>
        <% @event.attendees.each do |attendee| %>
            <li><%= attendee.name %></li>
        <% end %>
    </ol>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEventsOdin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


  </head>

  <body>
    <header>
      <%= link_to 'Home', root_path %>
      <% if user_signed_in? %>
        <%= link_to 'My Created Events', my_created_events_path %>
        <%= link_to 'My Attended Events', my_events_path %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
        <%= current_user.name %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path %>
        <%= link_to 'Sign Up', new_user_registration_path %>
      <% end %>
    </header>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    
    <%= yield %>
  </body>
</html>